import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import React from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";

const SpaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SpaceGrotesk.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
